language: node_js
cache: npm
node_js:
  - node
git:
  depth: 5
jobs:
  include:
    - stage: run unit tests
      script: npm test
    - stage: lint types
      script: npm run lint-types
after_success:
  - bash <(curl -s https://codecov.io/bash)
